app = "notesbackend-h4sgtq"

[build]
  dockerfile = "Dockerfile" # Ensure a valid Dockerfile exists in the root directory

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true