# fly.toml app configuration file generated for notesbackend-h4sgtq on 2025-01-08T14:24:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notesbackend-h4sgtq'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
